require:
  - rubocop-rspec
  - rubocop-thread_safety

AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'bin/*'
    - 'script/**/*'
    - 'vendor/**/*'
    - 'spec/**/*'
    - 'tmp/**/*'
    - '**/Rakefile'
    - '**/Gemfile'
    - '*.gemspec'
    - 'node_modules/**/*'
  CacheRootDirectory: tmp/cache/rubocop
Layout/InitialIndentation:
  Enabled: true
  Exclude:
    - 'spec/**/*'
# ファイルの先頭に空行を入れるのは禁止
Layout/LeadingEmptyLines:
  Enabled: true
Style/ImplicitRuntimeError:
  Enabled: true
