version: 2.1

common: &common
  working_directory: ~/workspace
  parallelism: 1
  resource_class: small
  steps:
    - checkout
    - restore_cache:
        keys:
          - bundle-v1-{{ checksum "ruby_branch_coverage.gemspec" }}

    - run:
        name: Build gem dependencies
        command: |
          gem install bundler
          bundle lock
          bundle config --local path '.bundle'
          bundle check || bundle install --jobs 4
          bundle clean

    - save_cache:
        key: bundle-v1-{{ checksum "ruby_branch_coverage.gemspec" }}
        paths:
          - .bundle

    - run:
        name: Run tests
        command: |
          mkdir coverage
          bundle exec rspec

jobs:
  test_3_2:
    docker:
      - image: cimg/ruby:3.2
    <<: *common

  upload_coveralls:
    working_directory: ~/workspace
    docker:
      - image: cimg/ruby:3.2
    steps:
      - attach_workspace:
          at: ~/workspace
      - run:
          name: Run upload coveralls
          command: |
            curl -k https://coveralls.io/webhook?repo_token=$COVERALLS_REPO_TOKEN -d "payload[build_num]=$CIRCLE_BUILD_NUM&payload[status]=done"

workflows:
  version: 2
  build-and-test:
    jobs:
      - test_3_2
      - upload_coveralls:
          requires:
            - test_3_2
